language: php

env:
  global:
    - SYMFONY_PHPUNIT_DIR=$HOME/.phpunit-bridge

matrix:
  fast_finish: true
  include:
    - php: "7.1"
    - php: "7.2"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.phpunit-bridge

before_install:
  - if [[ -v $STABILITY ]]; then composer config minimum-stability $STABILITY; fi;
  - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/simple-phpunit -v
