version: "3.3"
services:
  phpunit7.1:
    entrypoint: ./vendor/bin/simple-phpunit -v
    build:
      context: .
      dockerfile: Dockerfile
      args:
        php_version: 7.1
  phpunit7.2:
    entrypoint: ./vendor/bin/simple-phpunit -v
    build:
      context: .
      dockerfile: Dockerfile
      args:
        php_version: 7.2