version: "3.3"
services:
  composer:
    entrypoint: composer update --prefer-lowest --no-interaction
    volumes:
    - .:/var/php
    build:
      context: .
      dockerfile: Dockerfile
      args:
        php_version: 7.3